### ISSUE TITLE
Setup not implemented

### ISSUE THREAD

**Issue by clarkd** [RichardSlater/Markdig.SyntaxHighlighting#2]
Getting an error with the most recent version of MarkDig:

`Method 'Setup' in type 'Markdig.SyntaxHighlighting.SyntaxHighlightingExtension' from assembly 'Markdig.SyntaxHighlighting, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.`

**Comment by clarkd** [comment]
PR open #3

**Comment by RichardSlater** [comment]
Thank You
