### ISSUE TITLE
No color on type names

### ISSUE THREAD

**Issue by automagisk** [RichardSlater/Markdig.SyntaxHighlighting#8]
Hi, thanks for making this extensions! I have a small problem with color on type names. They all just get black like this:

![image](https://user-images.githubusercontent.com/4305279/35297844-8db3a018-0080-11e8-9471-9aa0b18f2b26.png)

Is that just the way it is or have I done something wrong?

This is the commonmark I'm using:

\```c#
namespace Amido.VersionDashboard.Web.Domain {
    public interface IConfigProvider {
        string GetSetting(string appSetting);
    }
}
\```

**Comment by RichardSlater** [comment]
The styling of the code uses [ColorCode by Bashir Souid](https://github.com/RichardSlater/ColorCodePortable) it is possible to write alternative stylesheets for ColorCode, I've never seen anyone do that though so it's not exposed as an option through this extension.
